// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: acl/types.proto

import { NeoFsV2Refs } from '../refs/types_types';

type ChecksumType = NeoFsV2Refs.ChecksumType;

class BinaryWriter {
  private buffer: Uint8Array = new Uint8Array(1024);
  private position: number = 0;

  private ensureCapacity(needed: number): void {
    const required = this.position + needed;
    if (required <= this.buffer.length) return;
    let newSize = this.buffer.length * 2;
    while (newSize < required) newSize *= 2;
    const newBuffer = new Uint8Array(newSize);
    for (let i = 0; i < this.position; i++) {
      newBuffer[i] = this.buffer[i];
    }
    this.buffer = newBuffer;
  }

  /** Hermes: TypedArray#set from another buffer/view can throw RangeError on large or offset views. */
  private appendAll(src: Uint8Array): void {
    const n = src.length;
    const start = this.position;
    for (let i = 0; i < n; i++) {
      this.buffer[start + i] = src[i];
    }
    this.position += n;
  }

  private writeVarint(value: number): void {
    while (value > 127) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = (value & 127) | 128;
      value >>>= 7;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = value & 127;
  }

  private writeVarintBigInt(value: bigint): void {
    while (value > 127n) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = Number(value & 127n) | 128;
      value >>= 7n;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = Number(value & 127n);
  }

  writeDouble(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 1); // wire type 1
    this.ensureCapacity(8);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    view.setFloat64(0, value, true); // little endian
    this.position += 8;
  }

  writeFloat(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 5); // wire type 5
    this.ensureCapacity(4);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    view.setFloat32(0, value, true); // little endian
    this.position += 4;
  }

  writeInt32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeInt64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeUint32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeUint64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeBool(fieldNumber: number, value: boolean): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value ? 1 : 0);
  }

  writeString(fieldNumber: number, value: string): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = this.encodeString(value);
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.appendAll(bytes);
  }

  writeBytes(fieldNumber: number, value: Uint8Array): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    this.writeVarint(value.length);
    this.ensureCapacity(value.length);
    this.appendAll(value);
  }

  writeMessage(fieldNumber: number, value: any): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = value.serializeBinary();
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.appendAll(bytes);
  }

  writeEnum(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  private encodeString(str: string): Uint8Array {
    // Manual UTF-8 encoding (React Native compatible)
    const bytes: number[] = [];
    for (let i = 0; i < str.length; i++) {
      let codePoint = str.charCodeAt(i);
      if (codePoint >= 0xD800 && codePoint <= 0xDBFF && i + 1 < str.length) {
        const next = str.charCodeAt(i + 1);
        if (next >= 0xDC00 && next <= 0xDFFF) {
          codePoint = 0x10000 + ((codePoint - 0xD800) << 10) + (next - 0xDC00);
          i++;
        }
      }
      if (codePoint < 0x80) {
        bytes.push(codePoint);
      } else if (codePoint < 0x800) {
        bytes.push(0xC0 | (codePoint >> 6), 0x80 | (codePoint & 0x3F));
      } else if (codePoint < 0x10000) {
        bytes.push(0xE0 | (codePoint >> 12), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      } else {
        bytes.push(0xF0 | (codePoint >> 18), 0x80 | ((codePoint >> 12) & 0x3F), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      }
    }
    return new Uint8Array(bytes);
  }

  getResultBuffer(): Uint8Array {
    return this.buffer.slice(0, this.position);
  }
}

class BinaryReader {
  buffer: Uint8Array;
  position: number = 0;

  constructor(data: Uint8Array) {
    this.buffer = data;
  }

  readVarint(): number {
    let result = 0;
    let shift = 0;
    while (this.position < this.buffer.length) {
      const byte = this.buffer[this.position++];
      result |= (byte & 127) << shift;
      if ((byte & 128) === 0) break;
      shift += 7;
    }
    return result;
  }

  readVarintBigInt(): bigint {
    let result = 0n;
    let shift = 0n;
    while (this.position < this.buffer.length) {
      const byte = BigInt(this.buffer[this.position++]);
      result |= (byte & 127n) << shift;
      if ((byte & 128n) === 0n) break;
      shift += 7n;
    }
    return result;
  }

  readDouble(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    this.position += 8;
    return view.getFloat64(0, true); // little endian
  }

  readFloat(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    this.position += 4;
    return view.getFloat32(0, true); // little endian
  }

  readInt32(): number {
    return this.readVarint();
  }

  readInt64(): bigint {
    return this.readVarintBigInt();
  }

  readUint32(): number {
    return this.readVarint();
  }

  readUint64(): bigint {
    return this.readVarintBigInt();
  }

  readBool(): boolean {
    return this.readVarint() !== 0;
  }

  readString(): string {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return this.decodeString(bytes);
  }

  private decodeString(bytes: Uint8Array): string {
    // Manual UTF-8 decoding (React Native compatible)
    let result = '';
    let i = 0;
    while (i < bytes.length) {
      const byte1 = bytes[i++];
      if (byte1 < 0x80) {
        result += String.fromCharCode(byte1);
      } else if ((byte1 & 0xE0) === 0xC0) {
        const byte2 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x1F) << 6) | byte2);
      } else if ((byte1 & 0xF0) === 0xE0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x0F) << 12) | (byte2 << 6) | byte3);
      } else if ((byte1 & 0xF8) === 0xF0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        const byte4 = bytes[i++] & 0x3F;
        const codePoint = ((byte1 & 0x07) << 18) | (byte2 << 12) | (byte3 << 6) | byte4;
        result += String.fromCharCode(0xD800 + ((codePoint - 0x10000) >> 10), 0xDC00 + ((codePoint - 0x10000) & 0x3FF));
      }
    }
    return result;
  }

  readBytes(): Uint8Array {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return bytes;
  }

  readMessage<T>(deserialize: (data: Uint8Array) => T): T {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return deserialize(bytes);
  }

  readEnum(): number {
    return this.readVarint();
  }

  readInt32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getInt32(0, true); // little-endian
  }

  readInt64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigInt64(0, true); // little-endian
  }

  readUint32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getUint32(0, true); // little-endian
  }

  readUint64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigUint64(0, true); // little-endian
  }

  skipField(wireType: number): void {
    switch (wireType) {
      case 0: // Varint
        this.readVarint();
        break;
      case 1: // 64-bit
        this.position += 8;
        break;
      case 2: // Length-delimited
        const length = this.readVarint();
        this.position += length;
        break;
      case 3: // Start group (deprecated, just skip)
        // Groups are deprecated in proto3, skip without reading
        break;
      case 4: // End group (deprecated, just skip)
        // Groups are deprecated in proto3, skip without reading
        break;
      case 5: // 32-bit
        this.position += 4;
        break;
      default:
        throw new Error(`Unknown wire type: ${wireType}`);
    }
  }
}

export namespace NeoFsV2Acl {

export enum Role {
  Role_ROLE_UNSPECIFIED = 0,
  Role_USER = 1,
  Role_SYSTEM = 2,
  Role_OTHERS = 3,
}

export enum MatchType {
  MatchType_MATCH_TYPE_UNSPECIFIED = 0,
  MatchType_STRING_EQUAL = 1,
  MatchType_STRING_NOT_EQUAL = 2,
  MatchType_NOT_PRESENT = 3,
  MatchType_NUM_GT = 4,
  MatchType_NUM_GE = 5,
  MatchType_NUM_LT = 6,
  MatchType_NUM_LE = 7,
}

export enum Operation {
  Operation_OPERATION_UNSPECIFIED = 0,
  Operation_GET = 1,
  Operation_HEAD = 2,
  Operation_PUT = 3,
  Operation_DELETE = 4,
  Operation_SEARCH = 5,
  Operation_GETRANGE = 6,
  Operation_GETRANGEHASH = 7,
}

export enum Action {
  Action_ACTION_UNSPECIFIED = 0,
  Action_ALLOW = 1,
  Action_DENY = 2,
}

export enum HeaderType {
  HeaderType_HEADER_UNSPECIFIED = 0,
  HeaderType_REQUEST = 1,
  HeaderType_OBJECT = 2,
  HeaderType_SERVICE = 3,
}

export interface EACLRecord {
  Operation: Operation;
  Action: Action;
  Filters: EACLRecord_Filter[];
  Targets: EACLRecord_Target[];
}

export class EACLRecordImpl implements EACLRecord {
  Operation!: Operation;
  Action!: Action;
  Filters!: EACLRecord_Filter[];
  Targets!: EACLRecord_Target[];

  constructor(data?: Partial<EACLRecord>) {
    this.Operation = data?.Operation ?? 0;
    this.Action = data?.Action ?? 0;
    this.Filters = data?.Filters ?? [];
    this.Targets = data?.Targets ?? [];
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Operation !== 0) {
      writer.writeEnum(1, this.Operation);
    }
    if (this.Action !== 0) {
      writer.writeEnum(2, this.Action);
    }
    for (const item of this.Filters) {
      writer.writeMessage(3, item);
    }
    for (const item of this.Targets) {
      writer.writeMessage(4, item);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): EACLRecordImpl {
    const reader = new BinaryReader(data);
    const message = new EACLRecordImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Operation
          if (wireType === 0) { // Varint
            message.Operation = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Action
          if (wireType === 0) { // Varint
            message.Action = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Filters
          if (wireType === 2) { // Length-delimited
            message.Filters.push(reader.readMessage(EACLRecord_FilterImpl.deserializeBinary));
          } else {
            reader.skipField(wireType);
          }
          break;
        case 4: // Targets
          if (wireType === 2) { // Length-delimited
            message.Targets.push(reader.readMessage(EACLRecord_TargetImpl.deserializeBinary));
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): EACLRecord {
    return {
      Operation: this.Operation,
      Action: this.Action,
      Filters: this.Filters,
      Targets: this.Targets
    };
  }

}

export interface EACLRecord_Filter {
  HeaderType: HeaderType;
  MatchType: MatchType;
  Key: string;
  Value: string;
}

export class EACLRecord_FilterImpl implements EACLRecord_Filter {
  HeaderType!: HeaderType;
  MatchType!: MatchType;
  Key!: string;
  Value!: string;

  constructor(data?: Partial<EACLRecord_Filter>) {
    this.HeaderType = data?.HeaderType ?? 0;
    this.MatchType = data?.MatchType ?? 0;
    this.Key = data?.Key ?? "";
    this.Value = data?.Value ?? "";
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.HeaderType !== 0) {
      writer.writeEnum(1, this.HeaderType);
    }
    if (this.MatchType !== 0) {
      writer.writeEnum(2, this.MatchType);
    }
    if (this.Key !== "") {
      writer.writeString(3, this.Key);
    }
    if (this.Value !== "") {
      writer.writeString(4, this.Value);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): EACLRecord_FilterImpl {
    const reader = new BinaryReader(data);
    const message = new EACLRecord_FilterImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // HeaderType
          if (wireType === 0) { // Varint
            message.HeaderType = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // MatchType
          if (wireType === 0) { // Varint
            message.MatchType = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Key
          if (wireType === 2) { // Length-delimited
            message.Key = reader.readString();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 4: // Value
          if (wireType === 2) { // Length-delimited
            message.Value = reader.readString();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): EACLRecord_Filter {
    return {
      HeaderType: this.HeaderType,
      MatchType: this.MatchType,
      Key: this.Key,
      Value: this.Value
    };
  }

}

export interface EACLRecord_Target {
  Role: Role;
  Keys: Uint8Array[];
}

export class EACLRecord_TargetImpl implements EACLRecord_Target {
  Role!: Role;
  Keys!: Uint8Array[];

  constructor(data?: Partial<EACLRecord_Target>) {
    this.Role = data?.Role ?? 0;
    this.Keys = data?.Keys ?? [];
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Role !== 0) {
      writer.writeEnum(1, this.Role);
    }
    for (const item of this.Keys) {
      writer.writeBytes(2, item);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): EACLRecord_TargetImpl {
    const reader = new BinaryReader(data);
    const message = new EACLRecord_TargetImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Role
          if (wireType === 0) { // Varint
            message.Role = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Keys
          if (wireType === 2) { // Length-delimited
            message.Keys.push(reader.readBytes());
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): EACLRecord_Target {
    return {
      Role: this.Role,
      Keys: this.Keys
    };
  }

}

export interface EACLTable {
  Version?: NeoFsV2Refs.Version;
  ContainerId?: NeoFsV2Refs.ContainerID;
  Records: EACLRecord[];
}

export class EACLTableImpl implements EACLTable {
  Version?: NeoFsV2Refs.Version;
  ContainerId?: NeoFsV2Refs.ContainerID;
  Records!: EACLRecord[];

  constructor(data?: Partial<EACLTable>) {
    this.Version = data?.Version ?? undefined;
    this.ContainerId = data?.ContainerId ?? undefined;
    this.Records = data?.Records ?? [];
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Version) {
      writer.writeMessage(1, this.Version);
    }
    if (this.ContainerId) {
      writer.writeMessage(2, this.ContainerId);
    }
    for (const item of this.Records) {
      writer.writeMessage(3, item);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): EACLTableImpl {
    const reader = new BinaryReader(data);
    const message = new EACLTableImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Version
          if (wireType === 2) { // Length-delimited
            message.Version = reader.readMessage(NeoFsV2Refs.VersionImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // ContainerId
          if (wireType === 2) { // Length-delimited
            message.ContainerId = reader.readMessage(NeoFsV2Refs.ContainerIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Records
          if (wireType === 2) { // Length-delimited
            message.Records.push(reader.readMessage(EACLRecordImpl.deserializeBinary));
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): EACLTable {
    return {
      Version: this.Version,
      ContainerId: this.ContainerId,
      Records: this.Records
    };
  }

}

export interface BearerToken {
  Body?: BearerToken_Body;
  Signature?: NeoFsV2Refs.Signature;
}

export class BearerTokenImpl implements BearerToken {
  Body?: BearerToken_Body;
  Signature?: NeoFsV2Refs.Signature;

  constructor(data?: Partial<BearerToken>) {
    this.Body = data?.Body ?? undefined;
    this.Signature = data?.Signature ?? undefined;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Body) {
      writer.writeMessage(1, this.Body);
    }
    if (this.Signature) {
      writer.writeMessage(2, this.Signature);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): BearerTokenImpl {
    const reader = new BinaryReader(data);
    const message = new BearerTokenImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Body
          if (wireType === 2) { // Length-delimited
            message.Body = reader.readMessage(BearerToken_BodyImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Signature
          if (wireType === 2) { // Length-delimited
            message.Signature = reader.readMessage(NeoFsV2Refs.SignatureImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): BearerToken {
    return {
      Body: this.Body,
      Signature: this.Signature
    };
  }

}

export interface BearerToken_Body {
  EaclTable?: EACLTable;
  OwnerId?: NeoFsV2Refs.OwnerID;
  Lifetime?: BearerToken_Body_TokenLifetime;
  Issuer?: NeoFsV2Refs.OwnerID;
}

export class BearerToken_BodyImpl implements BearerToken_Body {
  EaclTable?: EACLTable;
  OwnerId?: NeoFsV2Refs.OwnerID;
  Lifetime?: BearerToken_Body_TokenLifetime;
  Issuer?: NeoFsV2Refs.OwnerID;

  constructor(data?: Partial<BearerToken_Body>) {
    this.EaclTable = data?.EaclTable ?? undefined;
    this.OwnerId = data?.OwnerId ?? undefined;
    this.Lifetime = data?.Lifetime ?? undefined;
    this.Issuer = data?.Issuer ?? undefined;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.EaclTable) {
      writer.writeMessage(1, this.EaclTable);
    }
    if (this.OwnerId) {
      writer.writeMessage(2, this.OwnerId);
    }
    if (this.Lifetime) {
      writer.writeMessage(3, this.Lifetime);
    }
    if (this.Issuer) {
      writer.writeMessage(4, this.Issuer);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): BearerToken_BodyImpl {
    const reader = new BinaryReader(data);
    const message = new BearerToken_BodyImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // EaclTable
          if (wireType === 2) { // Length-delimited
            message.EaclTable = reader.readMessage(EACLTableImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // OwnerId
          if (wireType === 2) { // Length-delimited
            message.OwnerId = reader.readMessage(NeoFsV2Refs.OwnerIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Lifetime
          if (wireType === 2) { // Length-delimited
            message.Lifetime = reader.readMessage(BearerToken_Body_TokenLifetimeImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 4: // Issuer
          if (wireType === 2) { // Length-delimited
            message.Issuer = reader.readMessage(NeoFsV2Refs.OwnerIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): BearerToken_Body {
    return {
      EaclTable: this.EaclTable,
      OwnerId: this.OwnerId,
      Lifetime: this.Lifetime,
      Issuer: this.Issuer
    };
  }

}

export interface BearerToken_Body_TokenLifetime {
  Exp: bigint;
  Nbf: bigint;
  Iat: bigint;
}

export class BearerToken_Body_TokenLifetimeImpl implements BearerToken_Body_TokenLifetime {
  Exp!: bigint;
  Nbf!: bigint;
  Iat!: bigint;

  constructor(data?: Partial<BearerToken_Body_TokenLifetime>) {
    this.Exp = data?.Exp ?? 0n;
    this.Nbf = data?.Nbf ?? 0n;
    this.Iat = data?.Iat ?? 0n;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Exp !== 0n) {
      writer.writeUint64(1, this.Exp);
    }
    if (this.Nbf !== 0n) {
      writer.writeUint64(2, this.Nbf);
    }
    if (this.Iat !== 0n) {
      writer.writeUint64(3, this.Iat);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): BearerToken_Body_TokenLifetimeImpl {
    const reader = new BinaryReader(data);
    const message = new BearerToken_Body_TokenLifetimeImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Exp
          if (wireType === 0) { // Varint
            message.Exp = reader.readUint64();
          } else if (wireType === 1) { // 64-bit
            message.Exp = reader.readUint64Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Nbf
          if (wireType === 0) { // Varint
            message.Nbf = reader.readUint64();
          } else if (wireType === 1) { // 64-bit
            message.Nbf = reader.readUint64Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Iat
          if (wireType === 0) { // Varint
            message.Iat = reader.readUint64();
          } else if (wireType === 1) { // 64-bit
            message.Iat = reader.readUint64Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): BearerToken_Body_TokenLifetime {
    return {
      Exp: this.Exp,
      Nbf: this.Nbf,
      Iat: this.Iat
    };
  }

}

} // namespace NeoFsV2Acl
