// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: reputation/service.proto

import { GrpcClient } from 'grpc-react-native';
import { AnnounceIntermediateResultRequestImpl, AnnounceIntermediateResultResponseImpl, AnnounceLocalTrustRequestImpl, AnnounceLocalTrustResponseImpl } from './service_types';

export class ReputationServiceClient {
  constructor(private client: GrpcClient) {}

  async announceLocalTrust(request: AnnounceLocalTrustRequestImpl): Promise<AnnounceLocalTrustResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.reputation.ReputationService/AnnounceLocalTrust',
      request.serializeBinary()
    );
    return AnnounceLocalTrustResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async announceIntermediateResult(request: AnnounceIntermediateResultRequestImpl): Promise<AnnounceIntermediateResultResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.reputation.ReputationService/AnnounceIntermediateResult',
      request.serializeBinary()
    );
    return AnnounceIntermediateResultResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

