// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: accounting/service.proto

import { GrpcClient } from 'grpc-react-native';
import { BalanceRequestImpl, BalanceResponseImpl } from './service_types';

export class AccountingServiceClient {
  constructor(private client: GrpcClient) {}

  async balance(request: BalanceRequestImpl): Promise<BalanceResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.accounting.AccountingService/Balance',
      request.serializeBinary()
    );
    return BalanceResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

