// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: refs/types.proto

class BinaryWriter {
  private buffer: Uint8Array = new Uint8Array(1024);
  private position: number = 0;

  private ensureCapacity(needed: number): void {
    const required = this.position + needed;
    if (required <= this.buffer.length) return;
    let newSize = this.buffer.length * 2;
    while (newSize < required) newSize *= 2;
    const newBuffer = new Uint8Array(newSize);
    for (let i = 0; i < this.position; i++) {
      newBuffer[i] = this.buffer[i];
    }
    this.buffer = newBuffer;
  }

  /** Hermes: TypedArray#set from another buffer/view can throw RangeError on large or offset views. */
  private appendAll(src: Uint8Array): void {
    const n = src.length;
    const start = this.position;
    for (let i = 0; i < n; i++) {
      this.buffer[start + i] = src[i];
    }
    this.position += n;
  }

  private writeVarint(value: number): void {
    while (value > 127) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = (value & 127) | 128;
      value >>>= 7;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = value & 127;
  }

  private writeVarintBigInt(value: bigint): void {
    while (value > 127n) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = Number(value & 127n) | 128;
      value >>= 7n;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = Number(value & 127n);
  }

  writeDouble(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 1); // wire type 1
    this.ensureCapacity(8);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    view.setFloat64(0, value, true); // little endian
    this.position += 8;
  }

  writeFloat(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 5); // wire type 5
    this.ensureCapacity(4);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    view.setFloat32(0, value, true); // little endian
    this.position += 4;
  }

  writeInt32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeInt64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeUint32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeUint64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeBool(fieldNumber: number, value: boolean): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value ? 1 : 0);
  }

  writeString(fieldNumber: number, value: string): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = this.encodeString(value);
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.appendAll(bytes);
  }

  writeBytes(fieldNumber: number, value: Uint8Array): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    this.writeVarint(value.length);
    this.ensureCapacity(value.length);
    this.appendAll(value);
  }

  writeMessage(fieldNumber: number, value: any): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = value.serializeBinary();
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.appendAll(bytes);
  }

  writeEnum(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  private encodeString(str: string): Uint8Array {
    // Manual UTF-8 encoding (React Native compatible)
    const bytes: number[] = [];
    for (let i = 0; i < str.length; i++) {
      let codePoint = str.charCodeAt(i);
      if (codePoint >= 0xD800 && codePoint <= 0xDBFF && i + 1 < str.length) {
        const next = str.charCodeAt(i + 1);
        if (next >= 0xDC00 && next <= 0xDFFF) {
          codePoint = 0x10000 + ((codePoint - 0xD800) << 10) + (next - 0xDC00);
          i++;
        }
      }
      if (codePoint < 0x80) {
        bytes.push(codePoint);
      } else if (codePoint < 0x800) {
        bytes.push(0xC0 | (codePoint >> 6), 0x80 | (codePoint & 0x3F));
      } else if (codePoint < 0x10000) {
        bytes.push(0xE0 | (codePoint >> 12), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      } else {
        bytes.push(0xF0 | (codePoint >> 18), 0x80 | ((codePoint >> 12) & 0x3F), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      }
    }
    return new Uint8Array(bytes);
  }

  getResultBuffer(): Uint8Array {
    return this.buffer.slice(0, this.position);
  }
}

class BinaryReader {
  buffer: Uint8Array;
  position: number = 0;

  constructor(data: Uint8Array) {
    this.buffer = data;
  }

  readVarint(): number {
    let result = 0;
    let shift = 0;
    while (this.position < this.buffer.length) {
      const byte = this.buffer[this.position++];
      result |= (byte & 127) << shift;
      if ((byte & 128) === 0) break;
      shift += 7;
    }
    return result;
  }

  readVarintBigInt(): bigint {
    let result = 0n;
    let shift = 0n;
    while (this.position < this.buffer.length) {
      const byte = BigInt(this.buffer[this.position++]);
      result |= (byte & 127n) << shift;
      if ((byte & 128n) === 0n) break;
      shift += 7n;
    }
    return result;
  }

  readDouble(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    this.position += 8;
    return view.getFloat64(0, true); // little endian
  }

  readFloat(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    this.position += 4;
    return view.getFloat32(0, true); // little endian
  }

  readInt32(): number {
    return this.readVarint();
  }

  readInt64(): bigint {
    return this.readVarintBigInt();
  }

  readUint32(): number {
    return this.readVarint();
  }

  readUint64(): bigint {
    return this.readVarintBigInt();
  }

  readBool(): boolean {
    return this.readVarint() !== 0;
  }

  readString(): string {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return this.decodeString(bytes);
  }

  private decodeString(bytes: Uint8Array): string {
    // Manual UTF-8 decoding (React Native compatible)
    let result = '';
    let i = 0;
    while (i < bytes.length) {
      const byte1 = bytes[i++];
      if (byte1 < 0x80) {
        result += String.fromCharCode(byte1);
      } else if ((byte1 & 0xE0) === 0xC0) {
        const byte2 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x1F) << 6) | byte2);
      } else if ((byte1 & 0xF0) === 0xE0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x0F) << 12) | (byte2 << 6) | byte3);
      } else if ((byte1 & 0xF8) === 0xF0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        const byte4 = bytes[i++] & 0x3F;
        const codePoint = ((byte1 & 0x07) << 18) | (byte2 << 12) | (byte3 << 6) | byte4;
        result += String.fromCharCode(0xD800 + ((codePoint - 0x10000) >> 10), 0xDC00 + ((codePoint - 0x10000) & 0x3FF));
      }
    }
    return result;
  }

  readBytes(): Uint8Array {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return bytes;
  }

  readMessage<T>(deserialize: (data: Uint8Array) => T): T {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return deserialize(bytes);
  }

  readEnum(): number {
    return this.readVarint();
  }

  readInt32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getInt32(0, true); // little-endian
  }

  readInt64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigInt64(0, true); // little-endian
  }

  readUint32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getUint32(0, true); // little-endian
  }

  readUint64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigUint64(0, true); // little-endian
  }

  skipField(wireType: number): void {
    switch (wireType) {
      case 0: // Varint
        this.readVarint();
        break;
      case 1: // 64-bit
        this.position += 8;
        break;
      case 2: // Length-delimited
        const length = this.readVarint();
        this.position += length;
        break;
      case 3: // Start group (deprecated, just skip)
        // Groups are deprecated in proto3, skip without reading
        break;
      case 4: // End group (deprecated, just skip)
        // Groups are deprecated in proto3, skip without reading
        break;
      case 5: // 32-bit
        this.position += 4;
        break;
      default:
        throw new Error(`Unknown wire type: ${wireType}`);
    }
  }
}

export namespace NeoFsV2Refs {

export enum SignatureScheme {
  SignatureScheme_ECDSA_SHA512 = 0,
  SignatureScheme_ECDSA_RFC6979_SHA256 = 1,
  SignatureScheme_ECDSA_RFC6979_SHA256_WALLET_CONNECT = 2,
  SignatureScheme_N3 = 3,
}

export enum ChecksumType {
  ChecksumType_CHECKSUM_TYPE_UNSPECIFIED = 0,
  ChecksumType_TZ = 1,
  ChecksumType_SHA256 = 2,
}

export interface Address {
  ContainerId?: ContainerID;
  ObjectId?: ObjectID;
}

export class AddressImpl implements Address {
  ContainerId?: ContainerID;
  ObjectId?: ObjectID;

  constructor(data?: Partial<Address>) {
    this.ContainerId = data?.ContainerId ?? undefined;
    this.ObjectId = data?.ObjectId ?? undefined;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.ContainerId) {
      writer.writeMessage(1, this.ContainerId);
    }
    if (this.ObjectId) {
      writer.writeMessage(2, this.ObjectId);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): AddressImpl {
    const reader = new BinaryReader(data);
    const message = new AddressImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // ContainerId
          if (wireType === 2) { // Length-delimited
            message.ContainerId = reader.readMessage(ContainerIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // ObjectId
          if (wireType === 2) { // Length-delimited
            message.ObjectId = reader.readMessage(ObjectIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): Address {
    return {
      ContainerId: this.ContainerId,
      ObjectId: this.ObjectId
    };
  }

}

export interface ObjectID {
  Value: Uint8Array;
}

export class ObjectIDImpl implements ObjectID {
  Value!: Uint8Array;

  constructor(data?: Partial<ObjectID>) {
    this.Value = data?.Value ?? new Uint8Array(0);
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Value.length > 0) {
      writer.writeBytes(1, this.Value);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): ObjectIDImpl {
    const reader = new BinaryReader(data);
    const message = new ObjectIDImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Value
          if (wireType === 2) { // Length-delimited
            message.Value = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): ObjectID {
    return {
      Value: this.Value
    };
  }

}

export interface ContainerID {
  Value: Uint8Array;
}

export class ContainerIDImpl implements ContainerID {
  Value!: Uint8Array;

  constructor(data?: Partial<ContainerID>) {
    this.Value = data?.Value ?? new Uint8Array(0);
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Value.length > 0) {
      writer.writeBytes(1, this.Value);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): ContainerIDImpl {
    const reader = new BinaryReader(data);
    const message = new ContainerIDImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Value
          if (wireType === 2) { // Length-delimited
            message.Value = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): ContainerID {
    return {
      Value: this.Value
    };
  }

}

export interface OwnerID {
  Value: Uint8Array;
}

export class OwnerIDImpl implements OwnerID {
  Value!: Uint8Array;

  constructor(data?: Partial<OwnerID>) {
    this.Value = data?.Value ?? new Uint8Array(0);
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Value.length > 0) {
      writer.writeBytes(1, this.Value);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): OwnerIDImpl {
    const reader = new BinaryReader(data);
    const message = new OwnerIDImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Value
          if (wireType === 2) { // Length-delimited
            message.Value = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): OwnerID {
    return {
      Value: this.Value
    };
  }

}

export interface SubnetID {
  Value: number;
}

export class SubnetIDImpl implements SubnetID {
  Value!: number;

  constructor(data?: Partial<SubnetID>) {
    this.Value = data?.Value ?? 0;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Value !== 0) {
      writer.writeUint32(1, this.Value);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): SubnetIDImpl {
    const reader = new BinaryReader(data);
    const message = new SubnetIDImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Value
          if (wireType === 0) { // Varint
            message.Value = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Value = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): SubnetID {
    return {
      Value: this.Value
    };
  }

}

export interface Version {
  Major: number;
  Minor: number;
}

export class VersionImpl implements Version {
  Major!: number;
  Minor!: number;

  constructor(data?: Partial<Version>) {
    this.Major = data?.Major ?? 0;
    this.Minor = data?.Minor ?? 0;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Major !== 0) {
      writer.writeUint32(1, this.Major);
    }
    if (this.Minor !== 0) {
      writer.writeUint32(2, this.Minor);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): VersionImpl {
    const reader = new BinaryReader(data);
    const message = new VersionImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Major
          if (wireType === 0) { // Varint
            message.Major = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Major = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Minor
          if (wireType === 0) { // Varint
            message.Minor = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Minor = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): Version {
    return {
      Major: this.Major,
      Minor: this.Minor
    };
  }

}

export interface Signature {
  Key: Uint8Array;
  Sign: Uint8Array;
  Scheme: SignatureScheme;
}

export class SignatureImpl implements Signature {
  Key!: Uint8Array;
  Sign!: Uint8Array;
  Scheme!: SignatureScheme;

  constructor(data?: Partial<Signature>) {
    this.Key = data?.Key ?? new Uint8Array(0);
    this.Sign = data?.Sign ?? new Uint8Array(0);
    this.Scheme = data?.Scheme ?? 0;
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Key.length > 0) {
      writer.writeBytes(1, this.Key);
    }
    if (this.Sign.length > 0) {
      writer.writeBytes(2, this.Sign);
    }
    if (this.Scheme !== 0) {
      writer.writeEnum(3, this.Scheme);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): SignatureImpl {
    const reader = new BinaryReader(data);
    const message = new SignatureImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Key
          if (wireType === 2) { // Length-delimited
            message.Key = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Sign
          if (wireType === 2) { // Length-delimited
            message.Sign = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // Scheme
          if (wireType === 0) { // Varint
            message.Scheme = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): Signature {
    return {
      Key: this.Key,
      Sign: this.Sign,
      Scheme: this.Scheme
    };
  }

}

export interface SignatureRFC6979 {
  Key: Uint8Array;
  Sign: Uint8Array;
}

export class SignatureRFC6979Impl implements SignatureRFC6979 {
  Key!: Uint8Array;
  Sign!: Uint8Array;

  constructor(data?: Partial<SignatureRFC6979>) {
    this.Key = data?.Key ?? new Uint8Array(0);
    this.Sign = data?.Sign ?? new Uint8Array(0);
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Key.length > 0) {
      writer.writeBytes(1, this.Key);
    }
    if (this.Sign.length > 0) {
      writer.writeBytes(2, this.Sign);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): SignatureRFC6979Impl {
    const reader = new BinaryReader(data);
    const message = new SignatureRFC6979Impl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Key
          if (wireType === 2) { // Length-delimited
            message.Key = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Sign
          if (wireType === 2) { // Length-delimited
            message.Sign = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): SignatureRFC6979 {
    return {
      Key: this.Key,
      Sign: this.Sign
    };
  }

}

export interface Checksum {
  Type: ChecksumType;
  Sum: Uint8Array;
}

export class ChecksumImpl implements Checksum {
  Type!: ChecksumType;
  Sum!: Uint8Array;

  constructor(data?: Partial<Checksum>) {
    this.Type = data?.Type ?? 0;
    this.Sum = data?.Sum ?? new Uint8Array(0);
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Type !== 0) {
      writer.writeEnum(1, this.Type);
    }
    if (this.Sum.length > 0) {
      writer.writeBytes(2, this.Sum);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): ChecksumImpl {
    const reader = new BinaryReader(data);
    const message = new ChecksumImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Type
          if (wireType === 0) { // Varint
            message.Type = reader.readEnum();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // Sum
          if (wireType === 2) { // Length-delimited
            message.Sum = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): Checksum {
    return {
      Type: this.Type,
      Sum: this.Sum
    };
  }

}

} // namespace NeoFsV2Refs
