// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: netmap/service.proto

import { GrpcClient } from '@merl1231/grpc-react-native';
import { LocalNodeInfoRequestImpl, LocalNodeInfoResponseImpl, NetmapSnapshotRequestImpl, NetmapSnapshotResponseImpl, NetworkInfoRequestImpl, NetworkInfoResponseImpl } from './service_types';

export class NetmapServiceClient {
  constructor(private client: GrpcClient) {}

  async localNodeInfo(request: LocalNodeInfoRequestImpl): Promise<LocalNodeInfoResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.netmap.NetmapService/LocalNodeInfo',
      request.serializeBinary()
    );
    return LocalNodeInfoResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async networkInfo(request: NetworkInfoRequestImpl): Promise<NetworkInfoResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.netmap.NetmapService/NetworkInfo',
      request.serializeBinary()
    );
    return NetworkInfoResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async netmapSnapshot(request: NetmapSnapshotRequestImpl): Promise<NetmapSnapshotResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.netmap.NetmapService/NetmapSnapshot',
      request.serializeBinary()
    );
    return NetmapSnapshotResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

