// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: container/service.proto

import { GrpcClient } from 'grpc-react-native';
import { AnnounceUsedSpaceRequestImpl, AnnounceUsedSpaceResponseImpl, DeleteRequestImpl, DeleteResponseImpl, GetExtendedACLRequestImpl, GetExtendedACLResponseImpl, GetRequestImpl, GetResponseImpl, ListRequestImpl, ListResponseImpl, PutRequestImpl, PutResponseImpl, RemoveAttributeRequestImpl, RemoveAttributeResponseImpl, SetAttributeRequestImpl, SetAttributeResponseImpl, SetExtendedACLRequestImpl, SetExtendedACLResponseImpl } from './service_types';

export class ContainerServiceClient {
  constructor(private client: GrpcClient) {}

  async put(request: PutRequestImpl): Promise<PutResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/Put',
      request.serializeBinary()
    );
    return PutResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async delete(request: DeleteRequestImpl): Promise<DeleteResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/Delete',
      request.serializeBinary()
    );
    return DeleteResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async get(request: GetRequestImpl): Promise<GetResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/Get',
      request.serializeBinary()
    );
    return GetResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async list(request: ListRequestImpl): Promise<ListResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/List',
      request.serializeBinary()
    );
    return ListResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async setExtendedACL(request: SetExtendedACLRequestImpl): Promise<SetExtendedACLResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/SetExtendedACL',
      request.serializeBinary()
    );
    return SetExtendedACLResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async getExtendedACL(request: GetExtendedACLRequestImpl): Promise<GetExtendedACLResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/GetExtendedACL',
      request.serializeBinary()
    );
    return GetExtendedACLResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async announceUsedSpace(request: AnnounceUsedSpaceRequestImpl): Promise<AnnounceUsedSpaceResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/AnnounceUsedSpace',
      request.serializeBinary()
    );
    return AnnounceUsedSpaceResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async setAttribute(request: SetAttributeRequestImpl): Promise<SetAttributeResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/SetAttribute',
      request.serializeBinary()
    );
    return SetAttributeResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async removeAttribute(request: RemoveAttributeRequestImpl): Promise<RemoveAttributeResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.container.ContainerService/RemoveAttribute',
      request.serializeBinary()
    );
    return RemoveAttributeResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

