// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: audit/types.proto

import { NeoFsV2Refs } from '../refs/types_types';

type ChecksumType = NeoFsV2Refs.ChecksumType;

class BinaryWriter {
  private buffer: Uint8Array = new Uint8Array(1024);
  private position: number = 0;

  private ensureCapacity(needed: number): void {
    if (this.position + needed > this.buffer.length) {
      const newBuffer = new Uint8Array(this.buffer.length * 2);
      newBuffer.set(this.buffer);
      this.buffer = newBuffer;
    }
  }

  private writeVarint(value: number): void {
    while (value > 127) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = (value & 127) | 128;
      value >>>= 7;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = value & 127;
  }

  private writeVarintBigInt(value: bigint): void {
    while (value > 127n) {
      this.ensureCapacity(1);
      this.buffer[this.position++] = Number(value & 127n) | 128;
      value >>= 7n;
    }
    this.ensureCapacity(1);
    this.buffer[this.position++] = Number(value & 127n);
  }

  writeDouble(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 1); // wire type 1
    this.ensureCapacity(8);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    view.setFloat64(0, value, true); // little endian
    this.position += 8;
  }

  writeFloat(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 5); // wire type 5
    this.ensureCapacity(4);
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    view.setFloat32(0, value, true); // little endian
    this.position += 4;
  }

  writeInt32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeInt64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeUint32(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  writeUint64(fieldNumber: number, value: bigint): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarintBigInt(value);
  }

  writeBool(fieldNumber: number, value: boolean): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value ? 1 : 0);
  }

  writeString(fieldNumber: number, value: string): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = this.encodeString(value);
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.buffer.set(bytes, this.position);
    this.position += bytes.length;
  }

  writeBytes(fieldNumber: number, value: Uint8Array): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    this.writeVarint(value.length);
    this.ensureCapacity(value.length);
    this.buffer.set(value, this.position);
    this.position += value.length;
  }

  writeMessage(fieldNumber: number, value: any): void {
    this.writeVarint((fieldNumber << 3) | 2); // wire type 2
    const bytes = value.serializeBinary();
    this.writeVarint(bytes.length);
    this.ensureCapacity(bytes.length);
    this.buffer.set(bytes, this.position);
    this.position += bytes.length;
  }

  writeEnum(fieldNumber: number, value: number): void {
    this.writeVarint((fieldNumber << 3) | 0); // wire type 0
    this.writeVarint(value);
  }

  private encodeString(str: string): Uint8Array {
    // Manual UTF-8 encoding (React Native compatible)
    const bytes: number[] = [];
    for (let i = 0; i < str.length; i++) {
      let codePoint = str.charCodeAt(i);
      if (codePoint >= 0xD800 && codePoint <= 0xDBFF && i + 1 < str.length) {
        const next = str.charCodeAt(i + 1);
        if (next >= 0xDC00 && next <= 0xDFFF) {
          codePoint = 0x10000 + ((codePoint - 0xD800) << 10) + (next - 0xDC00);
          i++;
        }
      }
      if (codePoint < 0x80) {
        bytes.push(codePoint);
      } else if (codePoint < 0x800) {
        bytes.push(0xC0 | (codePoint >> 6), 0x80 | (codePoint & 0x3F));
      } else if (codePoint < 0x10000) {
        bytes.push(0xE0 | (codePoint >> 12), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      } else {
        bytes.push(0xF0 | (codePoint >> 18), 0x80 | ((codePoint >> 12) & 0x3F), 0x80 | ((codePoint >> 6) & 0x3F), 0x80 | (codePoint & 0x3F));
      }
    }
    return new Uint8Array(bytes);
  }

  getResultBuffer(): Uint8Array {
    return this.buffer.slice(0, this.position);
  }
}

class BinaryReader {
  buffer: Uint8Array;
  position: number = 0;

  constructor(data: Uint8Array) {
    this.buffer = data;
  }

  readVarint(): number {
    let result = 0;
    let shift = 0;
    while (this.position < this.buffer.length) {
      const byte = this.buffer[this.position++];
      result |= (byte & 127) << shift;
      if ((byte & 128) === 0) break;
      shift += 7;
    }
    return result;
  }

  readVarintBigInt(): bigint {
    let result = 0n;
    let shift = 0n;
    while (this.position < this.buffer.length) {
      const byte = BigInt(this.buffer[this.position++]);
      result |= (byte & 127n) << shift;
      if ((byte & 128n) === 0n) break;
      shift += 7n;
    }
    return result;
  }

  readDouble(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 8);
    this.position += 8;
    return view.getFloat64(0, true); // little endian
  }

  readFloat(): number {
    const view = new DataView(this.buffer.buffer, this.buffer.byteOffset + this.position, 4);
    this.position += 4;
    return view.getFloat32(0, true); // little endian
  }

  readInt32(): number {
    return this.readVarint();
  }

  readInt64(): bigint {
    return this.readVarintBigInt();
  }

  readUint32(): number {
    return this.readVarint();
  }

  readUint64(): bigint {
    return this.readVarintBigInt();
  }

  readBool(): boolean {
    return this.readVarint() !== 0;
  }

  readString(): string {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return this.decodeString(bytes);
  }

  private decodeString(bytes: Uint8Array): string {
    // Manual UTF-8 decoding (React Native compatible)
    let result = '';
    let i = 0;
    while (i < bytes.length) {
      const byte1 = bytes[i++];
      if (byte1 < 0x80) {
        result += String.fromCharCode(byte1);
      } else if ((byte1 & 0xE0) === 0xC0) {
        const byte2 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x1F) << 6) | byte2);
      } else if ((byte1 & 0xF0) === 0xE0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        result += String.fromCharCode(((byte1 & 0x0F) << 12) | (byte2 << 6) | byte3);
      } else if ((byte1 & 0xF8) === 0xF0) {
        const byte2 = bytes[i++] & 0x3F;
        const byte3 = bytes[i++] & 0x3F;
        const byte4 = bytes[i++] & 0x3F;
        const codePoint = ((byte1 & 0x07) << 18) | (byte2 << 12) | (byte3 << 6) | byte4;
        result += String.fromCharCode(0xD800 + ((codePoint - 0x10000) >> 10), 0xDC00 + ((codePoint - 0x10000) & 0x3FF));
      }
    }
    return result;
  }

  readBytes(): Uint8Array {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return bytes;
  }

  readMessage<T>(deserialize: (data: Uint8Array) => T): T {
    const length = this.readVarint();
    const bytes = this.buffer.slice(this.position, this.position + length);
    this.position += length;
    return deserialize(bytes);
  }

  readEnum(): number {
    return this.readVarint();
  }

  readInt32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getInt32(0, true); // little-endian
  }

  readInt64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigInt64(0, true); // little-endian
  }

  readUint32Fixed(): number {
    const bytes = this.buffer.slice(this.position, this.position + 4);
    this.position += 4;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getUint32(0, true); // little-endian
  }

  readUint64Fixed(): bigint {
    const bytes = this.buffer.slice(this.position, this.position + 8);
    this.position += 8;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    return view.getBigUint64(0, true); // little-endian
  }

  skipField(wireType: number): void {
    switch (wireType) {
      case 0: // Varint
        this.readVarint();
        break;
      case 1: // 64-bit
        this.position += 8;
        break;
      case 2: // Length-delimited
        const length = this.readVarint();
        this.position += length;
        break;
      case 5: // 32-bit
        this.position += 4;
        break;
      default:
        throw new Error(`Unknown wire type: ${wireType}`);
    }
  }
}

export namespace NeoFsV2Audit {

export interface DataAuditResult {
  Version?: NeoFsV2Refs.Version;
  AuditEpoch: bigint;
  ContainerId?: NeoFsV2Refs.ContainerID;
  PublicKey: Uint8Array;
  Complete: boolean;
  Requests: number;
  Retries: number;
  PassSg: NeoFsV2Refs.ObjectID[];
  FailSg: NeoFsV2Refs.ObjectID[];
  Hit: number;
  Miss: number;
  Fail: number;
  PassNodes: Uint8Array[];
  FailNodes: Uint8Array[];
}

export class DataAuditResultImpl implements DataAuditResult {
  Version?: NeoFsV2Refs.Version;
  AuditEpoch!: bigint;
  ContainerId?: NeoFsV2Refs.ContainerID;
  PublicKey!: Uint8Array;
  Complete!: boolean;
  Requests!: number;
  Retries!: number;
  PassSg!: NeoFsV2Refs.ObjectID[];
  FailSg!: NeoFsV2Refs.ObjectID[];
  Hit!: number;
  Miss!: number;
  Fail!: number;
  PassNodes!: Uint8Array[];
  FailNodes!: Uint8Array[];

  constructor(data?: Partial<DataAuditResult>) {
    this.Version = data?.Version ?? undefined;
    this.AuditEpoch = data?.AuditEpoch ?? 0n;
    this.ContainerId = data?.ContainerId ?? undefined;
    this.PublicKey = data?.PublicKey ?? new Uint8Array(0);
    this.Complete = data?.Complete ?? false;
    this.Requests = data?.Requests ?? 0;
    this.Retries = data?.Retries ?? 0;
    this.PassSg = data?.PassSg ?? [];
    this.FailSg = data?.FailSg ?? [];
    this.Hit = data?.Hit ?? 0;
    this.Miss = data?.Miss ?? 0;
    this.Fail = data?.Fail ?? 0;
    this.PassNodes = data?.PassNodes ?? [];
    this.FailNodes = data?.FailNodes ?? [];
  }

  serializeBinary(): Uint8Array {
    const writer = new BinaryWriter();

    if (this.Version) {
      writer.writeMessage(1, this.Version);
    }
    if (this.AuditEpoch !== 0n) {
      writer.writeUint64(2, this.AuditEpoch);
    }
    if (this.ContainerId) {
      writer.writeMessage(3, this.ContainerId);
    }
    if (this.PublicKey.length > 0) {
      writer.writeBytes(4, this.PublicKey);
    }
    if (this.Complete !== false) {
      writer.writeBool(5, this.Complete);
    }
    if (this.Requests !== 0) {
      writer.writeUint32(6, this.Requests);
    }
    if (this.Retries !== 0) {
      writer.writeUint32(7, this.Retries);
    }
    for (const item of this.PassSg) {
      writer.writeMessage(8, item);
    }
    for (const item of this.FailSg) {
      writer.writeMessage(9, item);
    }
    if (this.Hit !== 0) {
      writer.writeUint32(10, this.Hit);
    }
    if (this.Miss !== 0) {
      writer.writeUint32(11, this.Miss);
    }
    if (this.Fail !== 0) {
      writer.writeUint32(12, this.Fail);
    }
    for (const item of this.PassNodes) {
      writer.writeBytes(13, item);
    }
    for (const item of this.FailNodes) {
      writer.writeBytes(14, item);
    }
    return writer.getResultBuffer();
  }

  static deserializeBinary(data: Uint8Array): DataAuditResultImpl {
    const reader = new BinaryReader(data);
    const message = new DataAuditResultImpl();

    // Parse protobuf wire format
    while (reader.position < reader.buffer.length) {
      const tag = reader.readVarint();
      const fieldNumber = tag >>> 3;
      const wireType = tag & 7;

      switch (fieldNumber) {
        case 1: // Version
          if (wireType === 2) { // Length-delimited
            message.Version = reader.readMessage(NeoFsV2Refs.VersionImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 2: // AuditEpoch
          if (wireType === 0) { // Varint
            message.AuditEpoch = reader.readUint64();
          } else if (wireType === 1) { // 64-bit
            message.AuditEpoch = reader.readUint64Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 3: // ContainerId
          if (wireType === 2) { // Length-delimited
            message.ContainerId = reader.readMessage(NeoFsV2Refs.ContainerIDImpl.deserializeBinary);
          } else {
            reader.skipField(wireType);
          }
          break;
        case 4: // PublicKey
          if (wireType === 2) { // Length-delimited
            message.PublicKey = reader.readBytes();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 5: // Complete
          if (wireType === 0) { // Varint
            message.Complete = reader.readBool();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 6: // Requests
          if (wireType === 0) { // Varint
            message.Requests = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Requests = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 7: // Retries
          if (wireType === 0) { // Varint
            message.Retries = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Retries = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 8: // PassSg
          if (wireType === 2) { // Length-delimited
            message.PassSg.push(reader.readMessage(NeoFsV2Refs.ObjectIDImpl.deserializeBinary));
          } else {
            reader.skipField(wireType);
          }
          break;
        case 9: // FailSg
          if (wireType === 2) { // Length-delimited
            message.FailSg.push(reader.readMessage(NeoFsV2Refs.ObjectIDImpl.deserializeBinary));
          } else {
            reader.skipField(wireType);
          }
          break;
        case 10: // Hit
          if (wireType === 0) { // Varint
            message.Hit = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Hit = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 11: // Miss
          if (wireType === 0) { // Varint
            message.Miss = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Miss = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 12: // Fail
          if (wireType === 0) { // Varint
            message.Fail = reader.readUint32();
          } else if (wireType === 5) { // 32-bit
            message.Fail = reader.readUint32Fixed();
          } else {
            reader.skipField(wireType);
          }
          break;
        case 13: // PassNodes
          if (wireType === 2) { // Length-delimited
            message.PassNodes.push(reader.readBytes());
          } else {
            reader.skipField(wireType);
          }
          break;
        case 14: // FailNodes
          if (wireType === 2) { // Length-delimited
            message.FailNodes.push(reader.readBytes());
          } else {
            reader.skipField(wireType);
          }
          break;
        default:
          // Skip unknown fields
          reader.skipField(wireType);
          break;
      }
    }

    return message;
  }

  toObject(): DataAuditResult {
    return {
      Version: this.Version,
      AuditEpoch: this.AuditEpoch,
      ContainerId: this.ContainerId,
      PublicKey: this.PublicKey,
      Complete: this.Complete,
      Requests: this.Requests,
      Retries: this.Retries,
      PassSg: this.PassSg,
      FailSg: this.FailSg,
      Hit: this.Hit,
      Miss: this.Miss,
      Fail: this.Fail,
      PassNodes: this.PassNodes,
      FailNodes: this.FailNodes
    };
  }

}

} // namespace NeoFsV2Audit
