// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: object/service.proto

import { GrpcClient } from '@merl1231/grpc-react-native';
import { DeleteRequestImpl, DeleteResponseImpl, GetRangeHashRequestImpl, GetRangeHashResponseImpl, GetRangeRequestImpl, GetRangeResponseImpl, GetRequestImpl, GetResponseImpl, HeadRequestImpl, HeadResponseImpl, PutRequestImpl, PutResponseImpl, ReplicateRequestImpl, ReplicateResponseImpl, SearchRequestImpl, SearchResponseImpl, SearchV2RequestImpl, SearchV2ResponseImpl } from './service_types';

export class ObjectServiceClient {
  constructor(private client: GrpcClient) {}

  async* get(request: GetRequestImpl): AsyncGenerator<GetResponseImpl> {
    const stream = this.client.serverStreamCall(
      'neo.fs.v2.object.ObjectService/Get',
      request.serializeBinary()
    );
    for await (const response of stream) {
      if (response.done) {
        break; // End of stream
      }
      if (response.data) {
        yield GetResponseImpl.deserializeBinary(response.data as Uint8Array);
      }
    }
  }

  async put(requests: AsyncIterable<PutRequestImpl>): Promise<PutResponseImpl> {
    async function* serialize() {
      for await (const req of requests) {
        // Dense copy: Hermes/grpc bridge can choke on protobuf subviews.
        yield new Uint8Array(req.serializeBinary());
      }
    }
    const response = await this.client.clientStreamCall(
      'neo.fs.v2.object.ObjectService/Put',
      serialize()
    );
    return PutResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async delete(request: DeleteRequestImpl): Promise<DeleteResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.object.ObjectService/Delete',
      request.serializeBinary()
    );
    return DeleteResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async head(request: HeadRequestImpl): Promise<HeadResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.object.ObjectService/Head',
      request.serializeBinary()
    );
    return HeadResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async* search(request: SearchRequestImpl): AsyncGenerator<SearchResponseImpl> {
    const stream = this.client.serverStreamCall(
      'neo.fs.v2.object.ObjectService/Search',
      request.serializeBinary()
    );
    for await (const response of stream) {
      if (response.done) {
        break; // End of stream
      }
      if (response.data) {
        yield SearchResponseImpl.deserializeBinary(response.data as Uint8Array);
      }
    }
  }

  async searchV2(request: SearchV2RequestImpl): Promise<SearchV2ResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.object.ObjectService/SearchV2',
      request.serializeBinary()
    );
    return SearchV2ResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async* getRange(request: GetRangeRequestImpl): AsyncGenerator<GetRangeResponseImpl> {
    const stream = this.client.serverStreamCall(
      'neo.fs.v2.object.ObjectService/GetRange',
      request.serializeBinary()
    );
    for await (const response of stream) {
      if (response.done) {
        break; // End of stream
      }
      if (response.data) {
        yield GetRangeResponseImpl.deserializeBinary(response.data as Uint8Array);
      }
    }
  }

  async getRangeHash(request: GetRangeHashRequestImpl): Promise<GetRangeHashResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.object.ObjectService/GetRangeHash',
      request.serializeBinary()
    );
    return GetRangeHashResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

  async replicate(request: ReplicateRequestImpl): Promise<ReplicateResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.object.ObjectService/Replicate',
      request.serializeBinary()
    );
    return ReplicateResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

