// Code generated by protoc-gen-grpc-react-native. DO NOT EDIT.
// Generated from: session/service.proto

import { GrpcClient } from 'grpc-react-native';
import { CreateRequestImpl, CreateResponseImpl } from './service_types';

export class SessionServiceClient {
  constructor(private client: GrpcClient) {}

  async create(request: CreateRequestImpl): Promise<CreateResponseImpl> {
    const response = await this.client.unaryCall(
      'neo.fs.v2.session.SessionService/Create',
      request.serializeBinary()
    );
    return CreateResponseImpl.deserializeBinary(response.data as Uint8Array);
  }

}

